version: "3"
services:
    web:
        build: .
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
        ports:
            - "4200:4200"
            - "49153:49153"
        command: npm start
